### ISSUE TITLE
Feedback van tweedejaars

### ISSUE THREAD

**Issue by Stefan-Espant** [Metehan2003/fix-the-flow-wireflow#1]
**Top**

**Tip**
* Goed dat je een visuele weergave in Figma hebt, probeer voortaan eerst op papier een schets op te zetten. Figma biedt namelijk de mogelijkheid om je ontwerp pixel-perfect te maken. Hoeveel tijd ben je ermee kwijt?
* 

TODO voor Stefan :P

**Comment by Metehan2003** [comment]
Ik heb nu schetsen op papier gemaakt. Voor het figma ontwerp heb ik ongeveer een uur aan gewerkt.

De schetsen en figma ontwerp: 

https://github.com/Metehan2003/fix-the-flow-wireflow/wiki/Ontwerpen

**Comment by Metehan2003** [comment]
De figma ontwerp:
